[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "cd frontend && npm install && npm run build && cd ..",
  "npx prisma generate"
]

[start]
cmd = "node src/index.js"
